Finalizing Soft Delete
lionheart/django-lionheart-helpers pull request #9
Opened 2016-11-01 22:20 UTC by philiptyler

Added some key ideas I picked up from other soft delete projects and sitting down with some other TBT devs.

2016-11-01 23:36 UTC, philiptyler commented
@dlo this is ready for merge/dist whenever you get a moment
I was going to do it, but I realize I don't have PyPi permissions to do so

2016-11-02 19:51 UTC, dlo requested changes

2016-11-02 19:51 UTC, dlo commented
@philiptyler Didn't realize my comments didn't come through until I "added" the review. Oops! :)

2016-11-02 19:54 UTC, philiptyler commented on lionheart/models.py
> +        if not len(self):
agreed. defensive coding lol

2016-11-02 19:55 UTC, philiptyler commented on lionheart/models.py
> +        qs.__class__ = SoftDeleteQuerySet
super(SoftDeleteQuerySet, self).filter will return a django.models.QuerySet, so any chained calls wont use SoftDeleteQuerySet Logic.  By setting the class to SoftDeleteQuerySet, chained calls will use the correct overridden functions

2016-11-02 19:58 UTC, philiptyler commented on lionheart/models.py
> +        qs.__class__ = SoftDeleteQuerySet
Essentially we're just casting.
http://stackoverflow.com/questions/9165756/object-type-casting-in-python-after-reloading-a-module-for-on-the-fly-code-cha

2016-11-02 20:07 UTC, dlo commented on lionheart/models.py
> +        qs.__class__ = SoftDeleteQuerySet
Got it, makes sense. The superclass filter method returns a plain old QuerySet. A comment here is probably worthwhile.

2016-11-02 20:08 UTC, dlo commented on lionheart/models.py
> +    def _queryset_from_kwarg_contidtions(self, kwargs):
Minor typo :)

2016-11-02 20:12 UTC, dlo approved these changes

2016-11-02 20:12 UTC, dlo commented
Looks great! 🎉

2016-11-02 20:12 UTC, merged